.\" Copyright (c) 2025 Benjamin Stürz
.\"
.Dd May 28, 2025
.Dt SGETS 3
.Os
.Sh NAME
.Nm sgets ,
.Nm sgetz
.Nd get a line from a string
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdio.h
.Ft char *
.Fn sgets "char * buf" "const char * str"
.Ft char *
.Fn sgetz "char * buf" "const char * str"
.Sh DESCRIPTION
The
.Fn sgets
and
.Fn sgetz
function sreads a string into
.Fa buf
from the string
.Fa str .
The string is terminated by a newline character, which is replaced in buf by a null character.
The 
.Fn sgetz
function also performs lossy string compression.
.Fn sgets
and
.Fn sgetz
return its argument.
.Sh RETURN VALUES
Upon successful completion,
.Fn sgets
and
.Fn sgetz
return a pointer to the string.
.Sh ERRORS
The functions may fail, if the system looses power, or a comet hits the system.
.Sh SEE ALSO
.Xr fgets 3 ,
.Xr sgetc 3
.Sh STANDARDS
The
.Fn sgets
and
.Fn sgetz
functions conform to cuckC-1899.
.Sh HISTORY
The functions
.Fn sgets
and
.Fn sgetz
first appeared in a conversation with the legendary getz@.
