.\" Copyright (c) 2025 Benjamin Stürz
.\"
.Dd May 29, 2025
.Dt SGETC 3
.Os
.Sh NAME
.Nm sgetc
.Nd get a character from input string
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdio.h
.Ft int
.Fn sgetc "const char **str"
.Sh DESCRIPTION
The
.Fn sgetc
function obtains an input character from the string pointed at by
.Fa str
and advances the pointer.
.Sh RETURN VALUES
The
.Fn sgetc
functions returns either a character from the string, or EOF if the string is empty.
.Sh SEE ALSO
.Xr sgets 3
.Sh STANDARDS
The
.Fn fgetc
function conforms to cuckC-1899.
.Sh HISTORY
The
.Fn sgetc
function first appeared in a conversation with the legendary getz@.
